language: rust
cache: cargo
rust:
  - 1.26.0
  - stable
  - beta
  - nightly
env:
  - MONIKER_CARGO_FEATURES=""
  - MONIKER_CARGO_FEATURES="codespan im"
  - MONIKER_CARGO_FEATURES="default"
  - MONIKER_CARGO_FEATURES="default codespan im"
matrix:
  allow_failures:
    - rust: nightly
script:
  # moniker-derive
  - cargo build --manifest-path=moniker-derive/Cargo.toml --verbose
  - cargo test --manifest-path=moniker-derive/Cargo.toml --verbose
  # moniker
  - cargo build --manifest-path=moniker/Cargo.toml --no-default-features --features="$MONIKER_CARGO_FEATURES" --verbose
  - cargo test --manifest-path=moniker/Cargo.toml --no-default-features --features="$MONIKER_CARGO_FEATURES" --verbose
  # moniker examples
  - cargo build --manifest-path=moniker/Cargo.toml --no-default-features --features="$MONIKER_CARGO_FEATURES" --verbose --examples
  - cargo test --manifest-path=moniker/Cargo.toml --no-default-features --features="$MONIKER_CARGO_FEATURES" --verbose --examples
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ac9ac9e4198b308fe760
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
